### ISSUE TITLE
small bug: lowecase `shadow.js`/`typography.js` breaks default theme imports

### ISSUE THREAD

**Issue by JorchRL** [deleteman/the-hive#4]
commit f785a16e3742b1fee1979175373cc5fbdb5a1561 changed:

-`/src/theme/Shadows.js` to `shadows.js`. Same for `Typography.js` -> `typography.js`

but `theme.js` on the same folder imports their default name. 
```
import shadows from "./Shadows";
import typography from "./Typoraphy";
```
So either they should be changed back, or the imports on `theme.js` updated. I don't know whether the UI library expect the Uppercase imports somewhere else.

**Comment by deleteman** [comment]
Thanks Jorge, good eye. I don't understand how I didn't see the problem, but I've updated the code.
