### ISSUE TITLE
small fix: make repo filtering case insensitive

### ISSUE THREAD

**Issue by JorchRL** [deleteman/the-hive#5]
Currently the search for a repo feature is case-sensitive. Maybe making the filtering case-insensitive would make for a better UX? 

```js
// /api/repos,  findRepos()

if (q.trim() != "") { //are we filtering?
      filteredRepos = repos.filter(function filterFN(r) {
        return r.name.indexOf(q) != -1;
      });
    } else {
      filteredRepos = repos;
    }
```

![image](https://user-images.githubusercontent.com/27286509/176781379-27bce82b-408b-4641-986f-0b89a358e726.png)

![image](https://user-images.githubusercontent.com/27286509/176781452-36d54bb9-9c63-404b-8fab-4aaa5071b5d7.png)

After the change:

```js
if (q.trim() != "") { //are we filtering?
      filteredRepos = repos.filter(function filterFN(r) {
        // lowercase filtering
        return r.name.toLowerCase().indexOf(q.toLowerCase()) != -1;
      });
    } else {
      filteredRepos = repos;
    }
```

![image](https://user-images.githubusercontent.com/27286509/176783896-936b418d-152e-480d-9ac6-3ece658bbd17.png)
![image](https://user-images.githubusercontent.com/27286509/176783979-4e8a46c6-5823-48cc-8573-f7b340817c27.png)

:D

**Comment by deleteman** [comment]
I like it! Turn it into a PR and I'll merge it! Thanks!
While you're at it, I have a pending minor fix for the search, maybe you can also take care of it: right now I'm pulling all repos from a user, including their private ones. I don't think we should even look at them, since if they're private, I don't think they'll be interested in publishing them into the hive. So we need to filter out private repos BEFORE even getting to this point of your fix.

What do you think? Can you take care of that too?

**Comment by JorchRL** [comment]
Sure! I'll send the PR in a bit!

Regarding the fetching of the repos, As I understand, requesting the repos from an authenticated user should work with the "visibility" query parameter, but its not working (?). I'll try using "type" instead.

As an alternative. If I understand correctly [the `repo` scope for the OAuth token](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) grants full read/write access to both private and public repos. Do you want to limit the hive only to public repos?  I could change the scope to `public_repo`:

```ts
// /api/[...nextAuth].js

...

GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      authorization: {
        params: {
          // scope: 'repo read:user user:email read:org',
          scope: 'public_repo read:user user:email read:org'
        },
      },
    }),
```

**Comment by deleteman** [comment]
Ah crap, I had already added that, my bad, I forgot about it and thought I didn't do it, so I had an internal note about implementing that. So forget about it, it's already implemented :P

**Comment by JorchRL** [comment]
Noted! :D
